name: example
description: A new Flutter application.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bonfire:
    path: ".."
  fast_noise: ^1.0.1

dev_dependencies:
  test: any
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/player/
    - assets/images/enemy/
    - assets/images/npc/
    - assets/images/tile/
    - assets/images/tile_random/
    - assets/images/tiled/
    - assets/images/tiled/top_down/
    - assets/images/tiled/tileset/
    - assets/images/itens/
    - assets/images/lpc/body/
    - assets/images/lpc/feet/
    - assets/images/lpc/hair/
    - assets/images/lpc/leg/
    - assets/images/lpc/torco/
    - assets/images/lpc/head/
    - assets/images/lpc/gloves/
    - assets/images/multi_scenario/hero/
    - assets/images/multi_scenario/tile/
