name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame.
version: 2.12.0
homepage: https://bonfire-engine.github.io
repository: https://github.com/RafaelBarbosatec/bonfire
issue_tracker: https://github.com/RafaelBarbosatec/bonfire/issues
documentation: https://bonfire-engine.github.io

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.6.0
  tiledjsonreader: ^1.2.6
  http: ^0.13.5
  a_star_algorithm: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
