name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame.
version: 3.12.6
homepage: https://bonfire-engine.github.io
repository: https://github.com/RafaelBarbosatec/bonfire
issue_tracker: https://github.com/RafaelBarbosatec/bonfire/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  a_star_algorithm: ^0.4.1
  http: ^1.2.2
  flame: 1.23.0
  tiledjsonreader: ^1.4.1

dev_dependencies:
  flame_lint: ^1.2.1
  flutter_test:
    sdk: flutter

flutter:
