name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame.
version: 2.11.1
homepage: https://github.com/RafaelBarbosatec/bonfire

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.4.0
  tiledjsonreader: ^1.2.5
  http: ^0.13.5
  a_star_algorithm: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
