name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame.
version: 0.7.4
homepage: https://github.com/RafaelBarbosatec/bonfire

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.27.0
  ordered_set: ^2.0.0
  tiledjsonreader: ^0.0.8
  http: ^0.12.2
  shared_preferences: ^0.5.12

dev_dependencies:
  test: any

flutter:

  uses-material-design: true
